micronaut:
  application:
    name: server
  io:
    watch:
      paths: src/main
      restart: true
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
jsondb:
  path: ./data/db
crypto:
  user:
    salt: '"${USER_DATABASE_PASSWORD_SALT:pleaseChangeThisSecretForANewOne}"'